name: Build Docs

on:
  push:
    branches: [main]
    paths:
      - 'spec/**/*.yaml'
      - 'spec/gen/gen_docs.py'
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate markdown
        run: python scripts/generate_docs.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./generated_docs  # or wherever your script outputs
