name: Build Docs

on:
  push:
    branches: [main]
    paths:
      - 'src/spec/**/*.yaml'
      - 'src/spec/gen/gen_docs.py'
      - 'scripts/*.py'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mkdocs mkdocs-material

      - name: Generate markdown
        run: python scripts/generate_docs.py

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Upload built site to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site  # MkDocs outputs here by default

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2